routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Login routes
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

// Web
Route::group(['prefix' => '/', 'middleware' => 'web', 'namespace' => 'Web'], function () {

    Route::get('/', 'HomeController')->name('home');
    Route::post('/change-currency', 'HomeController@changeCurrency')->name('change-currency');

    // pages
    Route::get('/shop', 'ShopController')->name('shop');
    Route::post('/shop/filter', 'ShopController@filter')->name('shop.filter');

    Route::post('/cart/add', 'CartController@add')->name('cart.add');
    Route::get('/cart/remove/{uuid}', 'CartController@remove')->name('cart.remove');
    Route::get('/cart/qty/{uuid}/{qty}', 'CartController@qtyModify')->name('cart.qty');
//    Route::get('/cart/generate', 'CartController@generate')->name('cart.generate');

    Route::get('/cart', 'CartController')->name('cart');
    Route::get('/invoice-download/{uuid}','CartController@downloadInvoice')->name('invoice-download');

    Route::get('/product/{uuid}', 'ProductController')->name('product');
    Route::get('/faq', 'PageController@faq')->name('faq');
    Route::get('/about-us', 'PageController@aboutUs')->name('about-us');
    Route::get('/contact', 'PageController@contact')->name('contact');
    Route::post('/contact', 'PageController@submitContact')->name('contact');
    Route::get('/search', 'SearchController')->name('search');
    Route::get('/favourite', 'FavouriteController')->name('favourite');
    Route::get('/checkout', 'CheckoutController')->name('checkout');
    Route::post('/checkout/guest','CheckoutController@guest')->name('checkout.guest');

    # Call Route
        Route::get('payment', ['as' => 'payment', 'uses' => 'PaymentController@payment']);

# Status Route
    Route::get('payment/status', ['as' => 'payment.status', 'uses' => 'PaymentController@status']);

});
// return response image file
Route::get('/file/{response_type}/{storage}/{filename}', function ($responseType, $storage, $filename) {
    if (!Storage::disk($storage)->exists($filename)) {
        abort(404);
    }
    $file = Storage::disk($storage)->get($filename);
    $type = Storage::disk($storage)->mimeType($filename);
    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);
    if ($responseType == 'url') {
        return $response;
    } else {
        return response()->download(storage_path() . "\\app\\{$storage}\\{$filename}");
    }
})->name('file');


// return response image file
Route::get('/file/{response_type}/{storage}/{uuid}/{filename}', function ($responseType, $storage, $uuid, $filename) {
    if (!Storage::disk($storage)->exists($uuid . '/' . $filename)) {
        abort(404);
    }
    $file = Storage::disk($storage)->get($uuid . '/' . $filename);
    $type = Storage::disk($storage)->mimeType($uuid . '/' . $filename);
    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);
    if ($responseType == 'url') {
        return $response;
    } else {
        return response()->download(storage_path() . "\\app\\public\\{$storage}\\{$uuid}\\{$filename}");
    }
})->name('file.uuid');
// Admin
Route::group(['prefix' => '/admin', 'middleware' => ['auth', 'admin'], 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::get('/dashboard', 'DashboardController')->name('dashboard');
    Route::get('/bookings', 'BookingsController')->name('bookings');
    // category section
    Route::get('/categories', 'CategoriesController')->name('categories');
    Route::post('/create-category', 'CategoriesController@create')->name('create-category');
    Route::post('/update-category', 'CategoriesController@update')->name('update-category');
    Route::get('/category-edit/{uuid}', 'CategoriesController@edit')->name('category.edit');
    Route::get('/category-trash/{uuid}', 'CategoriesController@trash')->name('category.trash');
    Route::get('/category-restore/{uuid}', 'CategoriesController@restore')->name('category.restore');
    Route::get('/category-delete/{uuid}', 'CategoriesController@deletePermanent')->name('category.delete');

    // products section
    Route::get('/products', 'ProductsController')->name('products');
    Route::post('/create-product', 'ProductsController@create')->name('create-product');
    Route::post('/update-product', 'ProductsController@update')->name('update-product');
    Route::get('/product-edit/{uuid}', 'ProductsController@edit')->name('product.edit');
    Route::get('/product-trash/{uuid}', 'ProductsController@trash')->name('product.trash');
    Route::get('/product-restore/{uuid}', 'ProductsController@restore')->name('product.restore');
    Route::get('/product-delete/{uuid}', 'ProductsController@deletePermanent')->name('product.delete');
    Route::post('product/images-delete', ['uses' => 'ProductsController@deleteImages'])->name('product-images-delete');


    // colors section
    Route::get('/product-colors', 'ColorsController')->name('colors');
    Route::post('/create-product-colors', 'ColorsController@create')->name('create-color');
    Route::get('/color-delete/{id}', 'ColorsController@deletePermanent')->name('color.delete');


    // sizes section
    Route::get('/product-sizes', 'SizesController')->name('sizes');
    Route::post('/create-product-sizes', 'SizesController@create')->name('create-size');
    Route::get('/size-delete/{id}', 'SizesController@deletePermanent')->name('size.delete');


    Route::get('/guest-users', 'GuestUserController')->name('guest-users');
    Route::get('/reviews', 'ReviewsController')->name('reviews');
    Route::get('/transactions', 'TransactionsController')->name('transactions');
    Route::get('/user-carts', 'CartController')->name('user-carts');
    Route::post('/user-carts/items', 'CartController@items')->name('user-carts.items');
});

app/Models/Color.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Color extends Model
{
    protected $fillable = ['hexa','name'];

    public function product()
    {
        return $this->belongsToMany('Models/Products');
    }
}

app/Http/Controllers/Admin/ColorsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Color;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Redirect;

class ColorsController extends Controller
{
    public function __invoke()
    {
        $colors = Color::all();
        return view('admin.colors.index', compact('colors'));
    }

    public function create(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'hexa' => 'required',
        ]);
        Color::create($request->all());
        return back()->with([
            'type' => 'success',
            'messageTitle' => 'Category successfully created!',
            'messageText' => 'This Category is now available in the products section if its activated.',
            'code' => '201'
        ]);
    }

    public function deletePermanent($id)
    {
        $color = Color::find($id)->first();
        if ($color) {
            $color->delete();
            // return
            return Redirect::route('admin.colors')->with([
                'type' => 'success',
                'messageTitle' => 'color successfully Permanent Deleted!',
                'messageText' => 'This color is no more available for the services',
                'code' => '201'
            ]);
        } else {
            return abort(404);
        }
    }
}

resources/views/admin/colors/index.blade.php
@extends('admin.layouts.main')
@section('content')
    <form action="{{ route('admin.create-color')}}" method="POST" enctype="multipart/form-data">
        {{ csrf_field() }}
        <div class="form-body">
            <h3 class="box-title">Colors Info</h3>
            <hr class="m-t-0 m-b-10">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
                        <label class="control-label">Color Name</label>
                        <input type="text" class="form-control" placeholder="Name of the category" required autocomplete="off"
                               name="name" value="{{ old('name') }}">
                        @if ($errors->has('name'))
                            <span class="help-block">
                           {{ $errors->first('name') }}
                      </span>
                        @endif
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group {{ $errors->has('hexa') ? ' has-error' : '' }}">
                        <label class="control-label">Select Color</label><br>
                        <input type="text" class="colorpicker form-control" required autocomplete="off" name="hexa" value="{{ old('hexa') }}">
                        @if ($errors->has('hexa'))
                            <span class="help-block">
                           {{ $errors->first('hexa') }}
                      </span>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="form-actions">
            <button type="submit" class="btn btn-info"><i class="fa fa-check"></i> Save</button>
            <a href="{{route('admin.categories')}}" class="btn btn-default">Cancel</a>
        </div>
    </form>
@stop
@section('content2')
    <div class="white-box">
        <div class="table-responsive">
            <table id="demo-foo-addrow" class="table m-t-30 table-hover contact-list" data-page-size="10">
                <thead>
                <tr>
                    <th>No</th>
                    <th>Name</th>
                    <th>color</th>
                    <th>Manage</th>
                </tr>
                </thead>
                <tbody>
                @php ($id = 1)
                @foreach($colors as $color)
                    <tr>
                        <td>{{$id}}</td>
                        <td>{{$color->name}}</td>
                        <td>{{$color->hexa}}</td>
                        <td>
                            <button data="{{route('admin.color.delete',$color->id)}}" class="btn btn-danger btn-outline btn-circle m-r-5" onclick="confirmdelete('{{route('admin.color.delete',$color->id)}}')"><i class="ti-trash"></i></button>
                        </td>
                    </tr>
                    @php ($id++)
                @endforeach
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="7">
                        <div class="text-right">
                            <ul class="pagination"></ul>
                        </div>
                    </td>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>
@endsection
@section('header-plugin-css')
    <!--alerts CSS -->
    {!! Html::style('plugins/components/sweetalert/sweetalert.css') !!}

    {!! Html::style('plugins/components/jquery-asColorPicker-master/css/asColorPicker.css') !!}
@endsection
@section('js')
    <!-- Sweet-Alert  -->
    {!! Html::script('plugins/components/sweetalert/sweetalert.min.js') !!}
    {!! Html::script('plugins/components/sweetalert/jquery.sweet-alert.custom.js') !!}

    <!-- Color Picker Plugin JavaScript -->
    {!! Html::script('plugins/components/jquery-asColorPicker-master/libs/jquery-asColor.js') !!}
    {!! Html::script('plugins/components/jquery-asColorPicker-master/libs/jquery-asGradient.js') !!}
    {!! Html::script('plugins/components/jquery-asColorPicker-master/dist/jquery-asColorPicker.min.js') !!}
    <script>
        function confirmdelete(url) {
            swal({
                    title: "Are you sure you want to Delete",
                    text: "Your will not be able to recover this color after delete!",
                    type: "error",
                    showCancelButton: true,
                    confirmButtonClass: "btn-danger",
                    confirmButtonText: "Yes, delete it!",
                    closeOnConfirm: false
                },
                function () {
                    window.location.href = url;
                });
        }

        $(".colorpicker").asColorPicker();
    </script>
@stop