routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Login routes
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

// Web
Route::group(['prefix' => '/', 'middleware' => 'web', 'namespace' => 'Web'], function () {

    Route::get('/', 'HomeController')->name('home');
    Route::post('/change-currency', 'HomeController@changeCurrency')->name('change-currency');

    // pages
    Route::get('/shop', 'ShopController')->name('shop');
    Route::post('/shop/filter', 'ShopController@filter')->name('shop.filter');

    Route::post('/cart/add', 'CartController@add')->name('cart.add');
    Route::get('/cart/remove/{uuid}', 'CartController@remove')->name('cart.remove');
    Route::get('/cart/qty/{uuid}/{qty}', 'CartController@qtyModify')->name('cart.qty');
//    Route::get('/cart/generate', 'CartController@generate')->name('cart.generate');

    Route::get('/cart', 'CartController')->name('cart');
    Route::get('/invoice-download/{uuid}','CartController@downloadInvoice')->name('invoice-download');

    Route::get('/product/{uuid}', 'ProductController')->name('product');
    Route::get('/faq', 'PageController@faq')->name('faq');
    Route::get('/about-us', 'PageController@aboutUs')->name('about-us');
    Route::get('/contact', 'PageController@contact')->name('contact');
    Route::post('/contact', 'PageController@submitContact')->name('contact');
    Route::get('/search', 'SearchController')->name('search');
    Route::get('/favourite', 'FavouriteController')->name('favourite');
    Route::get('/checkout', 'CheckoutController')->name('checkout');
    Route::post('/checkout/guest','CheckoutController@guest')->name('checkout.guest');

    # Call Route
        Route::get('payment', ['as' => 'payment', 'uses' => 'PaymentController@payment']);

# Status Route
    Route::get('payment/status', ['as' => 'payment.status', 'uses' => 'PaymentController@status']);

});
// return response image file
Route::get('/file/{response_type}/{storage}/{filename}', function ($responseType, $storage, $filename) {
    if (!Storage::disk($storage)->exists($filename)) {
        abort(404);
    }
    $file = Storage::disk($storage)->get($filename);
    $type = Storage::disk($storage)->mimeType($filename);
    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);
    if ($responseType == 'url') {
        return $response;
    } else {
        return response()->download(storage_path() . "\\app\\{$storage}\\{$filename}");
    }
})->name('file');


// return response image file
Route::get('/file/{response_type}/{storage}/{uuid}/{filename}', function ($responseType, $storage, $uuid, $filename) {
    if (!Storage::disk($storage)->exists($uuid . '/' . $filename)) {
        abort(404);
    }
    $file = Storage::disk($storage)->get($uuid . '/' . $filename);
    $type = Storage::disk($storage)->mimeType($uuid . '/' . $filename);
    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);
    if ($responseType == 'url') {
        return $response;
    } else {
        return response()->download(storage_path() . "\\app\\public\\{$storage}\\{$uuid}\\{$filename}");
    }
})->name('file.uuid');
// Admin
Route::group(['prefix' => '/admin', 'middleware' => ['auth', 'admin'], 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::get('/dashboard', 'DashboardController')->name('dashboard');
    Route::get('/bookings', 'BookingsController')->name('bookings');
    // category section
    Route::get('/categories', 'CategoriesController')->name('categories');
    Route::post('/create-category', 'CategoriesController@create')->name('create-category');
    Route::post('/update-category', 'CategoriesController@update')->name('update-category');
    Route::get('/category-edit/{uuid}', 'CategoriesController@edit')->name('category.edit');
    Route::get('/category-trash/{uuid}', 'CategoriesController@trash')->name('category.trash');
    Route::get('/category-restore/{uuid}', 'CategoriesController@restore')->name('category.restore');
    Route::get('/category-delete/{uuid}', 'CategoriesController@deletePermanent')->name('category.delete');

    // products section
    Route::get('/products', 'ProductsController')->name('products');
    Route::post('/create-product', 'ProductsController@create')->name('create-product');
    Route::post('/update-product', 'ProductsController@update')->name('update-product');
    Route::get('/product-edit/{uuid}', 'ProductsController@edit')->name('product.edit');
    Route::get('/product-trash/{uuid}', 'ProductsController@trash')->name('product.trash');
    Route::get('/product-restore/{uuid}', 'ProductsController@restore')->name('product.restore');
    Route::get('/product-delete/{uuid}', 'ProductsController@deletePermanent')->name('product.delete');
    Route::post('product/images-delete', ['uses' => 'ProductsController@deleteImages'])->name('product-images-delete');


    // colors section
    Route::get('/product-colors', 'ColorsController')->name('colors');
    Route::post('/create-product-colors', 'ColorsController@create')->name('create-color');
    Route::get('/color-delete/{id}', 'ColorsController@deletePermanent')->name('color.delete');


    // sizes section
    Route::get('/product-sizes', 'SizesController')->name('sizes');
    Route::post('/create-product-sizes', 'SizesController@create')->name('create-size');
    Route::get('/size-delete/{id}', 'SizesController@deletePermanent')->name('size.delete');


    Route::get('/guest-users', 'GuestUserController')->name('guest-users');
    Route::get('/reviews', 'ReviewsController')->name('reviews');
    Route::get('/transactions', 'TransactionsController')->name('transactions');
    Route::get('/user-carts', 'CartController')->name('user-carts');
    Route::post('/user-carts/items', 'CartController@items')->name('user-carts.items');
});

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Categories;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\File;

class CategoriesController extends Controller
{
    public function __invoke()
    {
        $allcategories = Categories::all();
        $trashedcategories = Categories::onlyTrashed()->get();
        $categories = Categories::mainCategories()->pluck('name', 'uuid')->toArray();
        $selectCategory = array_merge([NULL  => 'Select parent category if this is child'], $categories);
        return view('admin.categories.index', compact('selectCategory', 'allcategories', 'trashedcategories'));
    }

    public function create(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'description' => '',
            'start_form' => 'required|numeric',
            'end_to' => 'numeric|nullable',
            'image' => 'required|image',
            'status' => 'required|in:0,1',
            'category' => '',
        ]);

        // Upload Images
        $request['file'] = NULL;
        if ($request->hasFile('image')) {
            $request['file'] = $request->name . '-' . uniqid() . '.' . $request->image->getClientOriginalExtension();
            Storage::disk('categories')->put($request['file'], File::get($request->image));
        }
        $data = [
            'name' => $request->name,
            'image' => $request['file'],
            'start_form' => $request->start_form,
            'end_to' => $request->end_to,
            'status' => $request->status,
            'parent_uuid' => $request->category,
            'description' => $request->description,
        ];
        Categories::create($data);
        return back()->with([
            'type' => 'success',
            'messageTitle' => 'Category successfully created!',
            'messageText' => 'This Category is now available in the products section if its activated.',
            'code' => '201'
        ]);
    }
    public function update(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'description' => '',
            'start_form' => 'required|numeric',
            'end_to' => 'numeric|nullable',
            'image' => 'nullable|image',
            'status' => 'required|in:0,1',
            'category' => '',
        ]);

        // Upload Images
        $data = [
            'name' => $request->name,
            'start_form' => $request->start_form,
            'end_to' => $request->end_to,
            'status' => $request->status,
            'parent_uuid' => $request->category,
            'description' => $request->description,
        ];

        if ($request->hasFile('image')) {
            $request['file'] = $request->name . '-' . uniqid() . '.' . $request->image->getClientOriginalExtension();
            Storage::disk('categories')->put($request['file'], File::get($request->image));
            $data['image'] = $request['file'];
        }

        Categories::where('uuid',$request->uuid)->update($data);
        return back()->with([
            'type' => 'success',
            'messageTitle' => 'Category successfully created!',
            'messageText' => 'This Category is now available in the products section if its activated.',
            'code' => '201'
        ]);
    }

    public function edit($uuid)
    {
        $category = Categories::where('uuid', $uuid)->first();
        $categories = Categories::mainCategories()->pluck('name', 'uuid')->toArray();
        $selectCategory = array_merge([NULL => 'Select parent category if this is child'], $categories);
        if ($category->count() > 0) {
            return view('admin.categories.edit', compact('category', 'selectCategory'));
        } else {
            return abort(404);
        }
    }

    public function trash($uuid)
    {
        $category = Categories::where('uuid', $uuid)->first();
        if ($category) {
            $category->update(['status' => 0]);
            $category->delete();
            // return
            return back()->with([
                'type' => 'success',
                'messageTitle' => 'Categories successfully Deleted!',
                'messageText' => 'This Categories is no more available for the services',
                'code' => '201'
            ]);
        } else {
            return abort(404);
        }
    }

    public function restore($uuid)
    {
        $category = Categories::withTrashed()->where('uuid', $uuid)->first();
        if ($category) {
            $category->restore();
            // return
            return back()->with([
                'type' => 'success',
                'messageTitle' => 'Categories successfully Restored!',
                'messageText' => 'This Categories is Now available for the services',
                'code' => '201'
            ]);
        } else {
            return abort(404);
        }
    }

    public function deletePermanent($uuid)
    {
        $category = Categories::withTrashed()->where('uuid', $uuid)->first();
        if ($category) {
            foreach ($category->products as $product){
                Storage::disk('products')->deleteDirectory($product->uuid);
                $product->forceDelete();
            }
            Storage::disk('categories')->delete($category->image);
            $category->forceDelete();
            // return
            return Redirect::route('admin.categories')->with([
                'type' => 'success',
                'messageTitle' => 'Categories successfully Permanent Deleted!',
                'messageText' => 'This Categories is no more available for the services',
                'code' => '201'
            ]);
        } else {
            return abort(404);
        }
    }
}

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.main')
@section('content')
    <form action="{{ route('admin.update-category')}}" method="POST" enctype="multipart/form-data">
        {{ csrf_field() }}
        {!! Form::hidden('uuid',$category->uuid) !!}
        <div class="form-body">
            <h3 class="box-title">Category Info</h3>
            <hr class="m-t-0 m-b-40">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
                        <label class="control-label">Category Name</label>
                        <input type="text" class="form-control" placeholder="Name of the category" required
                               name="name" value="{{ old('name',$category->name) }}">
                        @if ($errors->has('name'))
                            <span class="help-block">
                           {{ $errors->first('name') }}
                      </span>
                        @endif
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group {{ $errors->has('start_form') ? ' has-error' : '' }}">
                        <label class="control-label">Sart price from</label>
                        <input type="text" class="form-control" placeholder="Sart price from" required
                               name="start_form" value="{{ old('start_form',$category->start_form) }}">
                        @if ($errors->has('start_form'))
                            <span class="help-block">
                           {{ $errors->first('start_form') }}
                      </span>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group {{ $errors->has('end_to') ? ' has-error' : '' }}">
                        <label class="control-label">End price to</label>
                        <input type="text" class="form-control" placeholder="End price to" required
                               name="end_to" value="{{ old('end_to',$category->end_to) }}">
                        @if ($errors->has('end_to'))
                            <span class="help-block">
                           {{ $errors->first('end_to') }}
                      </span>
                        @endif
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group {{ $errors->has('status') ? ' has-error' : '' }}">
                        <label class="control-label">Category Status</label>
                        <div class="radio-list">
                            <label class="radio-inline p-0">
                                <div class="radio radio-info m-t-5">
                                    <input type="radio" name="status" id="radio1" value="1" @if(old('status',$category->status) == '1') checked @endif>
                                    <label for="radio1">Active</label>
                                </div>
                            </label>
                            <label class="radio-inline">
                                <div class="radio radio-info m-t-5">
                                    <input type="radio" name="status" id="radio2" value="0" @if(old('status',$category->status) == '0') checked @endif>
                                    <label for="radio2">Deactive</label>
                                </div>
                            </label>
                        </div>
                        @if ($errors->has('status'))
                            <span class="help-block">
                          {{ $errors->first('status') }}
                      </span>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group {{ $errors->has('image') ? ' has-error' : '' }}">
                        <label class="control-label">Category banner image</label>
                        <div class="input-group">
                            <label class="input-group-btn">
								<span class="btn btn-inverse">
									Browse&hellip; <input type="file" style="display: none;" name="image">
								</span>
                            </label>
                            <input type="text" class="form-control" readonly>
                        </div>
                        @if ($errors->has('image'))
                            <span class="help-block">
                          {{ $errors->first('image') }}
                      </span>
                        @endif
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group
                        {{ $errors->has('category') ? ' has-error' : '' }}">
                        <label class="control-label">Select Parent Category</label>
                        {!! Form::select('category', $selectCategory , old('category',$category->parent_uuid), [ 'class' => 'form-control' ]) !!}
                        @if ($errors->has('category'))
                            <span class="help-block">
                          {{ $errors->first('category') }}
                      </span>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group {{ $errors->has('description') ? ' has-error' : '' }}">
                        <label class="control-label">Description</label>
                        {!! Form::textarea('description', old('description',$category->description), ['rows' => '5', 'class' => 'form-control']) !!}
                        @if ($errors->has('description'))
                            <span class="help-block">
                          {{ $errors->first('description') }}
                      </span>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="form-actions">
            <button type="submit" class="btn btn-info"><i class="fa fa-check"></i> Save</button>
            <a href="{{route('admin.categories')}}" class="btn btn-default">Cancel</a>
        </div>
    </form>
@stop

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.main')
@section('content')
    <form action="{{ route('admin.create-category')}}" method="POST" enctype="multipart/form-data">
        {{ csrf_field() }}
        <div class="form-body">
            <h3 class="box-title">Category Info</h3>
            <hr class="m-t-0 m-b-40">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
                        <label class="control-label">Category Name</label>
                        <input type="text" class="form-control" placeholder="Name of the category" required
                               name="name" value="{{ old('name') }}">
                        @if ($errors->has('name'))
                            <span class="help-block">
                           {{ $errors->first('name') }}
                      </span>
                        @endif
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group {{ $errors->has('start_form') ? ' has-error' : '' }}">
                        <label class="control-label">Sart price from</label>
                        <input type="text" class="form-control" placeholder="Sart price from" required
                               name="start_form" value="{{ old('start_form') }}">
                        @if ($errors->has('start_form'))
                            <span class="help-block">
                           {{ $errors->first('start_form') }}
                      </span>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group {{ $errors->has('end_to') ? ' has-error' : '' }}">
                        <label class="control-label">End price to</label>
                        <input type="text" class="form-control" placeholder="End price to" required
                               name="end_to" value="{{ old('end_to') }}">
                        @if ($errors->has('end_to'))
                            <span class="help-block">
                           {{ $errors->first('end_to') }}
                      </span>
                        @endif
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group {{ $errors->has('status') ? ' has-error' : '' }}">
                        <label class="control-label">Category Status</label>
                        <div class="radio-list">
                            <label class="radio-inline p-0">
                                <div class="radio radio-info m-t-5">
                                    <input type="radio" name="status" id="radio1" value="1" @if(old('status')) checked @endif>
                                    <label for="radio1">Active</label>
                                </div>
                            </label>
                            <label class="radio-inline">
                                <div class="radio radio-info m-t-5">
                                    <input type="radio" name="status" id="radio2" value="0" @if(old('status')) checked @endif>
                                    <label for="radio2">Deactive</label>
                                </div>
                            </label>
                        </div>
                        @if ($errors->has('status'))
                            <span class="help-block">
                          {{ $errors->first('status') }}
                      </span>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group {{ $errors->has('image') ? ' has-error' : '' }}">
                        <label class="control-label">Category banner image</label>
                        <div class="input-group">
                            <label class="input-group-btn">
								<span class="btn btn-inverse">
									Browse&hellip; <input type="file" style="display: none;" name="image">
								</span>
                            </label>
                            <input type="text" class="form-control" readonly>
                        </div>
                        @if ($errors->has('image'))
                            <span class="help-block">
                          {{ $errors->first('image') }}
                      </span>
                        @endif
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group
                        {{ $errors->has('category') ? ' has-error' : '' }}">
                        <label class="control-label">Select Parent Category</label>
                        {!! Form::select('category', $selectCategory , old('category'), [ 'class' => 'form-control' ]) !!}
                        @if ($errors->has('category'))
                            <span class="help-block">
                          {{ $errors->first('category') }}
                      </span>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group {{ $errors->has('description') ? ' has-error' : '' }}">
                        <label class="control-label">Description</label>
                        {!! Form::textarea('description', old('description'), ['rows' => '5', 'class' => 'form-control']) !!}
                        @if ($errors->has('description'))
                            <span class="help-block">
                          {{ $errors->first('description') }}
                      </span>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="form-actions">
            <button type="submit" class="btn btn-info"><i class="fa fa-check"></i> Save</button>
            <a href="{{route('admin.categories')}}" class="btn btn-default">Cancel</a>
        </div>
    </form>
@stop
@section('content2')
    <div class="white-box">
        <ul class="nav customtab2 nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#categories" aria-controls="categories" role="tab" data-toggle="tab" aria-expanded="false"><span class="visible-xs"><i class="ti-home"></i></span><span class="hidden-xs"> All categories {{count($allcategories)}}</span></a></li>
            <li role="presentation" class=""><a href="#trashedcategories" aria-controls="trashedcategories" role="tab" data-toggle="tab" aria-expanded="false"><span class="visible-xs"><i class="ti-user"></i></span> <span class="hidden-xs">Trashed categories {{ $trashedcategories->count() }}</span></a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active fade in" id="categories">
                <div class="table-responsive">
                    <table id="demo-foo-addrow" class="table m-t-30 table-hover contact-list" data-page-size="10">
                        <thead>
                        <tr>
                            <th>No</th>
                            <th>Name</th>
                            <th>Is Active</th>
                            <th>Manage</th>
                        </tr>
                        </thead>
                        <tbody>
                        @php ($id = 1)
                        @foreach($allcategories as $category)
                            <tr>
                                <td>{{$id}}</td>
                                <td>{{$category->parent_uuid!=null? "--".$category->name:$category->name}}</td>
                                <td>{!! $category->status?'<span class="label label-success">Activate</span>':'<span class="label label-info m-r-10">Deactivate</span>' !!}</td>
                                <td>
                                    <a href="{{route('admin.category.edit',$category->uuid)}}" class="btn btn-info btn-outline btn-circle m-r-5" data-toggle="tooltip" data-original-title="Edit"><i class="ti-pencil-alt"></i></a>
                                    <a href="{{route('admin.category.trash',$category->uuid)}}" class="btn btn-primary btn-outline btn-circle m-r-5" data-toggle="tooltip" data-original-title="Move To Trash"><i class="ti-trash"></i></a>
                                </td>
                            </tr>
                            @php ($id++)
                        @endforeach
                        </tbody>
                        <tfoot>
                        <tr>
                            <td colspan="7">
                                <div class="text-right">
                                    <ul class="pagination"></ul>
                                </div>
                            </td>
                        </tr>
                        </tfoot>
                    </table>
                </div>
                <div class="clearfix"></div>
            </div>
            <div role="tabpanel" class="tab-pane fade" id="trashedcategories">
                <div class="table-responsive">
                    <table id="demo-foo-addrow" class="table m-t-30 table-hover contact-list" data-page-size="10">
                        <thead>
                        <tr>
                            <th>No</th>
                            <th>Name</th>
                            <th>Is Active</th>
                            <th>Manage</th>
                        </tr>
                        </thead>
                        <tbody>
                        @php ($id = 1)
                        @if($trashedcategories->count())
                            @foreach($trashedcategories as $categories)
                                <tr>
                                    <td>{{$id}}</td>
                                    <td>{{$categories->parent_uuid!=null? "--".$categories->name:$categories->name }}</td>
                                    <td>{!! $categories->status?'<span class="label label-success">Activate</span>':'<span class="label label-info m-r-10">Deactivate</span>' !!}</td>
                                    <td>
                                        <a href="{{route('admin.category.restore',$categories->uuid)}}" class="btn btn-success btn-outline btn-circle m-r-5" data-toggle="tooltip" data-original-title="Restore"> <i class="icon-reload"></i></a>
                                        <button data="{{route('admin.category.delete',$categories->uuid)}}" class="btn btn-danger btn-outline btn-circle m-r-5" onclick="confirmdelete('{{route('admin.category.delete',$categories->uuid)}}')"><i class="ti-trash"></i></button>
                                    </td>
                                </tr>
                                @php ($id++)
                            @endforeach
                        @else
                            <tr>
                                <td colspan="5" class="text-center">Empty Trashed</td>
                            </tr>
                        @endif
                        </tbody>
                        <tfoot>
                        <tr>
                            <td colspan="7">
                                <div class="text-right">
                                    <ul class="pagination"></ul>
                                </div>
                            </td>
                        </tr>
                        </tfoot>
                    </table>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
@endsection
@section('header-plugin-css')
    <!--alerts CSS -->
    {!! Html::style('plugins/components/sweetalert/sweetalert.css') !!}
@endsection
@section('js')
    <!-- Sweet-Alert  -->
    {!! Html::script('plugins/components/sweetalert/sweetalert.min.js') !!}
    {!! Html::script('plugins/components/sweetalert/jquery.sweet-alert.custom.js') !!}
    <script>
        document.getElementById("myForm").onkeypress = function (e) {
            var key = e.charCode || e.keyCode || 0;
            if (key == 13) {
                e.preventDefault();
            }
        }

        function confirmdelete(url) {
            swal({
                    title: "Are you sure you want to Delete",
                    text: "Your will not be able to recover this Category after delete!",
                    type: "error",
                    showCancelButton: true,
                    confirmButtonClass: "btn-danger",
                    confirmButtonText: "Yes, delete it!",
                    closeOnConfirm: false
                },
                function () {
                    window.location.href = url;
                });
        }
    </script>
@stop