routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Login routes
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

// Web
Route::group(['prefix' => '/', 'middleware' => 'web', 'namespace' => 'Web'], function () {

    Route::get('/', 'HomeController')->name('home');
    Route::post('/change-currency', 'HomeController@changeCurrency')->name('change-currency');

    // pages
    Route::get('/shop', 'ShopController')->name('shop');
    Route::post('/shop/filter', 'ShopController@filter')->name('shop.filter');

    Route::post('/cart/add', 'CartController@add')->name('cart.add');
    Route::get('/cart/remove/{uuid}', 'CartController@remove')->name('cart.remove');
    Route::get('/cart/qty/{uuid}/{qty}', 'CartController@qtyModify')->name('cart.qty');
//    Route::get('/cart/generate', 'CartController@generate')->name('cart.generate');

    Route::get('/cart', 'CartController')->name('cart');
    Route::get('/invoice-download/{uuid}','CartController@downloadInvoice')->name('invoice-download');

    Route::get('/product/{uuid}', 'ProductController')->name('product');
    Route::get('/faq', 'PageController@faq')->name('faq');
    Route::get('/about-us', 'PageController@aboutUs')->name('about-us');
    Route::get('/contact', 'PageController@contact')->name('contact');
    Route::post('/contact', 'PageController@submitContact')->name('contact');
    Route::get('/search', 'SearchController')->name('search');
    Route::get('/favourite', 'FavouriteController')->name('favourite');
    Route::get('/checkout', 'CheckoutController')->name('checkout');
    Route::post('/checkout/guest','CheckoutController@guest')->name('checkout.guest');

    # Call Route
        Route::get('payment', ['as' => 'payment', 'uses' => 'PaymentController@payment']);

# Status Route
    Route::get('payment/status', ['as' => 'payment.status', 'uses' => 'PaymentController@status']);

});
// return response image file
Route::get('/file/{response_type}/{storage}/{filename}', function ($responseType, $storage, $filename) {
    if (!Storage::disk($storage)->exists($filename)) {
        abort(404);
    }
    $file = Storage::disk($storage)->get($filename);
    $type = Storage::disk($storage)->mimeType($filename);
    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);
    if ($responseType == 'url') {
        return $response;
    } else {
        return response()->download(storage_path() . "\\app\\{$storage}\\{$filename}");
    }
})->name('file');


// return response image file
Route::get('/file/{response_type}/{storage}/{uuid}/{filename}', function ($responseType, $storage, $uuid, $filename) {
    if (!Storage::disk($storage)->exists($uuid . '/' . $filename)) {
        abort(404);
    }
    $file = Storage::disk($storage)->get($uuid . '/' . $filename);
    $type = Storage::disk($storage)->mimeType($uuid . '/' . $filename);
    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);
    if ($responseType == 'url') {
        return $response;
    } else {
        return response()->download(storage_path() . "\\app\\public\\{$storage}\\{$uuid}\\{$filename}");
    }
})->name('file.uuid');
// Admin
Route::group(['prefix' => '/admin', 'middleware' => ['auth', 'admin'], 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::get('/dashboard', 'DashboardController')->name('dashboard');
    Route::get('/bookings', 'BookingsController')->name('bookings');
    // category section
    Route::get('/categories', 'CategoriesController')->name('categories');
    Route::post('/create-category', 'CategoriesController@create')->name('create-category');
    Route::post('/update-category', 'CategoriesController@update')->name('update-category');
    Route::get('/category-edit/{uuid}', 'CategoriesController@edit')->name('category.edit');
    Route::get('/category-trash/{uuid}', 'CategoriesController@trash')->name('category.trash');
    Route::get('/category-restore/{uuid}', 'CategoriesController@restore')->name('category.restore');
    Route::get('/category-delete/{uuid}', 'CategoriesController@deletePermanent')->name('category.delete');

    // products section
    Route::get('/products', 'ProductsController')->name('products');
    Route::post('/create-product', 'ProductsController@create')->name('create-product');
    Route::post('/update-product', 'ProductsController@update')->name('update-product');
    Route::get('/product-edit/{uuid}', 'ProductsController@edit')->name('product.edit');
    Route::get('/product-trash/{uuid}', 'ProductsController@trash')->name('product.trash');
    Route::get('/product-restore/{uuid}', 'ProductsController@restore')->name('product.restore');
    Route::get('/product-delete/{uuid}', 'ProductsController@deletePermanent')->name('product.delete');
    Route::post('product/images-delete', ['uses' => 'ProductsController@deleteImages'])->name('product-images-delete');


    // colors section
    Route::get('/product-colors', 'ColorsController')->name('colors');
    Route::post('/create-product-colors', 'ColorsController@create')->name('create-color');
    Route::get('/color-delete/{id}', 'ColorsController@deletePermanent')->name('color.delete');


    // sizes section
    Route::get('/product-sizes', 'SizesController')->name('sizes');
    Route::post('/create-product-sizes', 'SizesController@create')->name('create-size');
    Route::get('/size-delete/{id}', 'SizesController@deletePermanent')->name('size.delete');


    Route::get('/guest-users', 'GuestUserController')->name('guest-users');
    Route::get('/reviews', 'ReviewsController')->name('reviews');
    Route::get('/transactions', 'TransactionsController')->name('transactions');
    Route::get('/user-carts', 'CartController')->name('user-carts');
    Route::post('/user-carts/items', 'CartController@items')->name('user-carts.items');
});

resources/views/admin/partials/footer.blade.php
<!-- Scripts -->
<!-- jQuery -->
{!! Html::script('admin-assets/plugins/components/jquery/dist/jquery.min.js') !!}
<!-- Bootstrap Core JavaScript -->
{!! Html::script('admin-assets/bootstrap/js/bootstrap.min.js') !!}
<!-- Menu Plugin JavaScript -->
{!! Html::script('admin-assets/plugins/components/sidebar-nav/dist/sidebar-nav.min.js') !!}
<!--slimscroll JavaScript -->
{!! Html::script('admin-assets/js/jquery.slimscroll.js') !!}
<!--Wave Effects -->
@yield('js')
<!-- toaster button js -->
{!! Html::script('admin-assets/plugins/components/toast-master/js/jquery.toast.js') !!}
{!! Html::script('admin-assets/js/waves.js') !!}
<!-- Custom Theme JavaScript -->
{!! Html::script('admin-assets/js/custom.min.js') !!}

<script>
    @if(Session::get('type')=='success')
    $.toast({
        heading: '{{Session::get('messageTitle')}}',
        text: '{!! Session::get('messageText') !!}',
        position: 'top-right',
        loaderBg: '#ff6849',
        icon: '{{Session::get('type')}}',
        hideAfter: 3500,
        stack: 6
    });
    @elseif(Session::get('type')=='error')
    $.toast({
        heading: '{{Session::get('messageTitle')}}',
        text: '{!! Session::get('messageText') !!}',
        position: 'top-right',
        loaderBg: '#ff6849',
        icon: '{{Session::get('type')}}',
        hideAfter: 14000
    });
    @endif
</script>

@yield('footer-js')
<!--Style Switcher -->
{!! Html::script('admin-assets/plugins/components/styleswitcher/jQuery.style.switcher.js') !!}

</body>
</html>

resources/views/admin/partials/header.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <link rel="icon" type="image/x-icon" sizes="16x16" href="plugins/images/favicon.ico">
    <title>OUR HANDICRAFTS</title>

    <!-- Bootstrap Core CSS -->
    {{ Html::style('admin-assets/bootstrap/css/bootstrap.min.css') }}
    <!-- animation CSS -->
    {{ Html::style('admin-assets/css/animate.css') }}
    <!-- Menu CSS -->
    {{ Html::style('admin-assets/plugins/components/sidebar-nav/dist/sidebar-nav.min.css') }}
    <!-- Toaster button css -->
    {!! Html::style('admin-assets/plugins/components/toast-master/css/jquery.toast.css') !!}
    @yield('header-plugin-css')
    <!-- Custom CSS -->
    {{ Html::style('admin-assets/css/style.css') }}
    <!-- color CSS -->
    {{ Html::style('admin-assets/css/colors/default.css') }}
    {{ Html::style('admin-assets/css/colors/blue.css') }}


    <!-- Custom at our handicrafts end CSS -->
    {{ Html::style('admin-assets/css/global.css') }}
	<!-- Custom Responsive CSS -->
    {{ Html::style('admin-assets/css/responsive.css') }}

</head>
<body class="fix-header po-body">
<!-- Preloader -->
<div class="preloader">
    <div class="cssload-speeding-wheel"></div>
</div>

resources/views/admin/partials/invoice-structure.blade.php
<table class="table" style="margin: 0 auto;" cellpadding="0" cellspacing="0">
    <tbody>
    <tr>
        <td style="border:0;border-bottom: 1px solid #DADFE4; padding: 10px 0;">
            <img src="{{ asset('images/logo.png') }}" alt="" height="80px"/>
        </td>
        <td align="right" style="border:0;border-bottom: 1px solid #DADFE4; padding: 10px 0;">
            <span style="color:#23B2F5;"><strong>INVOICE</strong></span><br>
            <span>{{ $currentBooking->order_id }}</span>
        </td>
    </tr>
    <tr>
        <td colspan="2">
            <table class="table" style="margin:0;">
                <tbody>
                <tr style="border:0;">
                    <td width="33%" style="border:0;">
                        <label style="margin-bottom:0; text-transform: uppercase;">Customer Name</label>
                        <p>{{ $currentBooking->guest->name }}</p>
                    </td>
                    <td width="33%" style="border:0;">
                        <label style="margin-bottom:0; text-transform: uppercase;">Email</label>
                        <p>{{ $currentBooking->guest->email }}</p>
                    </td>

                    <td width="33%" style="border:0;">
                        <label style="margin-bottom:0; text-transform: uppercase;">Contact</label>
                        <p>{{ $currentBooking->guest->number }}</p>
                    </td>

                </tr>

                <tr style="border:0;">
                    <td width="33%" style="border:0;">
                        <label style="margin-bottom:0; text-transform: uppercase;">Booking Total</label>
                        <p>Rs. {!! currency( $currentBooking->guest->cart->total_amount ,'USD','INR','!') !!} </p>
                    </td>
                    <td width="33%" style="border:0;">
                        <label style="margin-bottom:0; text-transform: uppercase;">Payment</label>
                        <p>Rs. {{ $currentBooking->payment->net_amount_debit }} </p>
                    </td>
                    <td width="33%" style="border:0;">
                        <label style="margin-bottom:0; text-transform: uppercase;">Payment Status</label>
                        <p>{{ $currentBooking->payment->status }}</p>
                    </td>
                </tr>

                <tr style="border:0;">
                    <td width="33%" style="border:0;">
                        <label style="margin-bottom:0; text-transform: uppercase;">TXNID</label>
                        <p>{{ $currentBooking->order_id }} </p>
                    </td>
                    <td width="33%" style="border:0;">
                        <label style="margin-bottom:0; text-transform: uppercase;">Currency Type</label>
                        <p>{{ $currentBooking->payment->currency_type ?? 'Not Available' }} </p>
                    </td>
                    <td width="33%" style="border:0;">
                        <label style="margin-bottom:0; text-transform: uppercase;">Currency Amount</label>
                        <p> {!! $currentBooking->payment->currency_type ? currency( $currentBooking->guest->cart->total_amount ,'USD',$currentBooking->payment->currency_type ) : 'Not Available!' !!} </p>
                    </td>
                </tr>
                <tr>
                    <td width="33%" style="border:0;">
                        <label style="margin-bottom:0; text-transform: uppercase;">Booking Date</label>
                        <p>{{ date('d M Y', strtotime($currentBooking->created_at)) }}</p>
                    </td>

                    <td width="33%" style="border:0;">
                        <label style="margin-bottom:0; text-transform: uppercase;">Pin Code</label>
                        <p>{{ $currentBooking->guest->code }}</p>
                    </td>
                    <td width="33%" style="border:0;">
                        <label style="margin-bottom:0; text-transform: uppercase;">City</label>
                        <p>{{ $currentBooking->guest->city }}</p>
                    </td>
                </tr>
                <tr>
                    <td width="30%" style="border:0;">
                        <label style="margin-bottom:0; text-transform: uppercase;">Country</label>
                        <p>{{ $currentBooking->guest->countryRelation->name}}</p>
                    </td>
                    <td width="30%" style="border:0;">
                        <label style="margin-bottom:0; text-transform: uppercase;">Address</label>
                        <p>{{ $currentBooking->guest->address }}</p>
                    </td>
                </tr>
                @if($currentBooking->payment->status == 'Failed')
                    <tr style="border:0;">
                        <td colspan="5" style="border:0;">
                            <label style="margin-bottom:0; text-transform: uppercase;">Reason Of Payment Fail</label>
                            <p>{{ $currentBooking->payment->data['error_Message'] }}</p>
                        </td>
                    </tr>
                @endif
                </tbody>
            </table>
        </td>
    </tr>
    <tr>
        <td colspan="2"
            style="background:#23B2F5; padding: 5px; text-transform: uppercase; font-weight: bold; color: #FFF;">
            Details
        </td>
    </tr>
    <tr>
        <td colspan="2">
            <table class="table">
                <thead>
                <tr>
                    <th class="text-center">#</th>
                    <th>Description</th>
                    <th>Price</th>
                    <th>Qty</th>
                    <th class="text-right">Total</th>
                </tr>
                </thead>
                <tbody>
                @forelse($currentBooking->guest->cart->items as $key => $item)
                    <tr>
                        <td class="text-center">{{ $key + 1  }}</td>
                        <td>{{ $item->product->name }}</td>
                        <td>Rs. {!! currency($item->product->discount_price,'USD','INR','!') !!}</td>
                        <td>{{ $item->qty }}</td>
                        <td class="text-right">
                            Rs. {!! currency($item->total_price * $item->qty,'USD','INR','!')  !!}</td>
                    </tr>
                @empty
                @endforelse
                <tr>
                    <td style="" align="right" colspan="2"><h4
                                style="font-family:'Rubik', sans-serif;margin:0;">Total</h4></td>
                    <td style="color:#23B2F5;" align="right" colspan="3"><h4
                                style="font-family:'Rubik', sans-serif;margin:0;">
                            Rs. {!! currency( $currentBooking->guest->cart->total_amount,'USD','INR','!') !!}</h4></td>

                </tr>
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="3" style="color:#9B9B9B;" align="center">2018 © ourhandicraft.com</td>
                </tr>
                </tfoot>
            </table>
        </td>
    </tr>
    </tbody>
</table>

resources/views/admin/partials/side-menu.blade.php
<nav class="navbar navbar-default navbar-static-top po-nav m-b-15">
    <div class="navbar-header">
        <div class="top-left-part">
            <!-- Logo -->
            <a class="logo" href="{{ route('admin.dashboard')  }}">
                <!-- Logo icon image, you can use font-icon also -->
                <b class="po-icon hidden">
                    <!--This is light logo icon-->
                    <img src="{{ asset('images/logo.png') }}" alt="home" class="light-logo img-responsive"/>
                </b>
                <!-- Logo text image you can use text also -->
                <span class="hidden-xs">
					<!--This is light logo text-->
                    <img src="{{ asset('images/logo.png') }}" alt="home" class="img-responsive light-logo"/>
                </span>
            </a>
        </div>
        <!-- /Logo -->
        <!-- Search input and Toggle icon -->
        <ul class="nav navbar-top-links navbar-left">
            <li><a href="javascript:void(0)" class="open-close waves-effect waves-light"><i class="ti-menu"></i></a></li>
            <li class="dropdown">
                <a class="dropdown-toggle waves-effect waves-light" data-toggle="dropdown" href="#"> <i class="mdi mdi-bell"></i>
                    <div class="notify"><span class="heartbit"></span> <span class="point"></span></div>
                </a>
            {{--<ul class="dropdown-menu mailbox animated bounceInDown">--}}
            {{--<li>--}}
            {{--<div class="drop-title">You have 4 new messages</div>--}}
            {{--</li>--}}
            {{--<li>--}}
            {{--<div class="message-center">--}}
            {{--<a href="#">--}}
            {{--<div class="user-img"><img src="plugins/images/users/pawandeep.jpg" alt="user" class="img-circle"> <span class="profile-status online pull-right"></span></div>--}}
            {{--<div class="mail-contnet">--}}
            {{--<h5>Pavan kumar</h5> <span class="mail-desc">Just see the my admin!</span> <span class="time">9:30 AM</span></div>--}}
            {{--</a>--}}
            {{--<a href="#">--}}
            {{--<div class="user-img"><img src="plugins/images/users/sonu.jpg" alt="user" class="img-circle"> <span class="profile-status busy pull-right"></span></div>--}}
            {{--<div class="mail-contnet">--}}
            {{--<h5>Sonu Nigam</h5> <span class="mail-desc">I've sung a song! See you at</span> <span class="time">9:10 AM</span></div>--}}
            {{--</a>--}}
            {{--<a href="#">--}}
            {{--<div class="user-img"><img src="plugins/images/users/arijit.jpg" alt="user" class="img-circle"> <span class="profile-status away pull-right"></span></div>--}}
            {{--<div class="mail-contnet">--}}
            {{--<h5>Arijit Sinh</h5> <span class="mail-desc">I am a singer!</span> <span class="time">9:08 AM</span></div>--}}
            {{--</a>--}}
            {{--<a href="#">--}}
            {{--<div class="user-img"><img src="plugins/images/users/pawandeep.jpg" alt="user" class="img-circle"> <span class="profile-status offline pull-right"></span></div>--}}
            {{--<div class="mail-contnet">--}}
            {{--<h5>Pavan kumar</h5> <span class="mail-desc">Just see the my admin!</span> <span class="time">9:02 AM</span></div>--}}
            {{--</a>--}}
            {{--</div>--}}
            {{--</li>--}}
            {{--<li>--}}
            {{--<a class="text-center" href="javascript:void(0);"> <strong>See all notifications</strong> <i class="fa fa-angle-right"></i> </a>--}}
            {{--</li>--}}
            {{--</ul>--}}
            <!-- /.dropdown-messages -->
            </li>
            <!-- .Task dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle waves-effect waves-light" data-toggle="dropdown" href="#"> <i class="mdi mdi-check-circle"></i>
                    <div class="notify"><span class="heartbit"></span><span class="point"></span></div>
                </a>
                {{--<ul class="dropdown-menu dropdown-tasks animated slideInUp">--}}
                {{--<li>--}}
                {{--<a href="#">--}}
                {{--<div>--}}
                {{--<p><strong>Task 1</strong> <span class="pull-right text-muted">40% Complete</span></p>--}}
                {{--<div class="progress progress-striped active">--}}
                {{--<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%"><span class="sr-only">40% Complete (success)</span></div>--}}
                {{--</div>--}}
                {{--</div>--}}
                {{--</a>--}}
                {{--</li>--}}
                {{--<li class="divider"></li>--}}
                {{--<li>--}}
                {{--<a href="#">--}}
                {{--<div>--}}
                {{--<p><strong>Task 2</strong> <span class="pull-right text-muted">20% Complete</span></p>--}}
                {{--<div class="progress progress-striped active">--}}
                {{--<div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%"><span class="sr-only">20% Complete</span></div>--}}
                {{--</div>--}}
                {{--</div>--}}
                {{--</a>--}}
                {{--</li>--}}
                {{--<li class="divider"></li>--}}
                {{--<li>--}}
                {{--<a href="#">--}}
                {{--<div>--}}
                {{--<p><strong>Task 3</strong> <span class="pull-right text-muted">60% Complete</span></p>--}}
                {{--<div class="progress progress-striped active">--}}
                {{--<div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%"><span class="sr-only">60% Complete (warning)</span></div>--}}
                {{--</div>--}}
                {{--</div>--}}
                {{--</a>--}}
                {{--</li>--}}
                {{--<li class="divider"></li>--}}
                {{--<li>--}}
                {{--<a href="#">--}}
                {{--<div>--}}
                {{--<p><strong>Task 4</strong> <span class="pull-right text-muted">80% Complete</span></p>--}}
                {{--<div class="progress progress-striped active">--}}
                {{--<div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%"><span class="sr-only">80% Complete (danger)</span></div>--}}
                {{--</div>--}}
                {{--</div>--}}
                {{--</a>--}}
                {{--</li>--}}
                {{--<li class="divider"></li>--}}
                {{--<li>--}}
                {{--<a class="text-center" href="#"> <strong>See All Tasks</strong> <i class="fa fa-angle-right"></i> </a>--}}
                {{--</li>--}}
                {{--</ul>--}}
            </li>
        </ul>
        <ul class="nav navbar-top-links navbar-right pull-right">
            <li>
                <form role="search" class="app-search hidden-sm hidden-xs m-r-10">
                    <input type="text" placeholder="Search..." class="form-control"> <a href=""><i class="fa fa-search"></i></a></form>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#"> <img src="{{asset('images/users/user-icon.png')}}" alt="user-img" width="36" class="img-circle"><b class="hidden-xs">{{ Auth::user()->first_name }}</b><span class="caret"></span> </a>
                <ul class="dropdown-menu dropdown-user animated flipInY">
                    <li>
                        <div class="dw-user-box">
                            <div class="u-img"><img src="{{asset('images/users/user-icon.png')}}" alt="{{ Auth::user()->name }}"/></div>
                            <div class="u-text">
                                <h4>{{ Auth::user()->name }}</h4>
                                <p class="text-muted">{{ Auth::user()->email }}</p>
                            </div>
                        </div>
                    </li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#"><i class="ti-user"></i> My Profile</a></li>
                    <li><a href="#"><i class="ti-wallet"></i> My Balance</a></li>
                    <li><a href="#"><i class="ti-email"></i> Inbox</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#"><i class="ti-settings"></i> Account Setting</a></li>
                    <li role="separator" class="divider"></li>
                    <li>
                        <a href="{{ route('logout') }}"><i class="fa fa-power-off"></i> Logout</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
    </div>
    <!-- /.navbar-header -->
    <!-- /.navbar-top-links -->
    <!-- /.navbar-static-side -->
</nav>
<!-- End Top Navigation -->
<!-- ============================================================== -->
<!-- Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav slimscrollsidebar">
        <div class="sidebar-head">
            <h3><span class="fa-fw open-close"><i class="ti-close ti-menu"></i></span> <span class="hide-menu">Navigation</span></h3>
        </div>
        <div class="user-profile">
            <div class="dropdown user-pro-body">
                <div><img src="{{asset('plugins/images/img4.jpg')}}" alt="user-img" class="img-circle"></div>
                <span>Steave Gection</span>
            </div>
        </div>
        <ul class="nav" id="side-menu">
            <li>
                <a href="{{Route('admin.dashboard')}}" class="waves-effect">
                    <i class="mdi mdi-av-timer fa-fw" data-icon="v"></i>
                    <span class="hide-menu">Dashboard</span>
                </a>
            </li>

            <li>
                <a href="{{route('admin.bookings')}}" class="waves-effect">
                    <i class="mdi mdi-calendar-check fa-fw"></i>
                    <span class="hide-menu">Bookings</span>
                </a>
            </li>

            <li>
                <a href="{{Route('admin.categories')}}" class="waves-effect">
                    <i class="mdi mdi-checkbox-multiple-marked-outline fa-fw"></i>
                    <span class="hide-menu">Categories</span>
                </a>
            </li>
            <li>
                <a href="{{Route('admin.products')}}" class="waves-effect">
                    <i class="fa-fw">P</i>
                    <span class="hide-menu">Products</span>
                </a>
            </li>

            {{--<li>--}}
                {{--<a href="{{Route('admin.guest-users')}}" class="waves-effect">--}}
                    {{--<i class="mdi mdi-emoticon fa-fw"></i>--}}
                    {{--<span class="hide-menu">Guest Users</span>--}}
                {{--</a>--}}
            {{--</li>--}}

            <li>
                <a href="{{Route('admin.user-carts')}}" class="waves-effect">
                    <i class="mdi mdi-cart-outline fa-fw" data-icon="v"></i>
                    <span class="hide-menu">User Carts</span>
                </a>
            </li>

            <li>
                <a href="{{Route('admin.colors')}}" class="waves-effect">
                    <i class="mdi mdi-format-color-fill fa-fw"></i>
                    <span class="hide-menu">Product Colors</span>
                </a>
            </li>

            <li>
                <a href="{{Route('admin.sizes')}}" class="waves-effect">
                    <i class="ti-layout-slider fa-fw"></i>
                    <span class="hide-menu">Product Sizes</span>
                </a>
            </li>


        </ul>
    </div>
</div>
<!-- ============================================================== -->
<!-- End Left Sidebar -->
<!-- ============================================================== -->